apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp
  namespace: volume-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus
      tier: frontend
  template:
    metadata:
      labels:
        app: bus
        tier: frontend
    spec:
      volumes:
        - name: newVolume
          persistentVolumeClaim:
            claimName: busapp-vol-pvc
      containers:
      - name: busapp
        image: learnitguide/busapp:1.0
        volumeMounts:
          - name: newVolume
            mountPath: "/tmp/data-test/"
        ports:
          - containerPort: 8001
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 2048Mi
