apiVersion: v1
kind: Service
meatada:
  name: bust-app-service
  namespace: volume-test
spec:
  selector:
      app: bus
      tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 8001